CREATE OR REPLACE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    code_validation VARCHAR(13) DEFAULT NULL,
    validated BOOLEAN NOT NULL DEFAULT FALSE
);